# Generated by Django 4.0.5 on 2022-06-30 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_rename_problems_problem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='status',
        ),
        migrations.AddField(
            model_name='problem',
            name='problemName',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='solveCount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
