# Generated by Django 4.0.5 on 2022-07-04 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_remove_problem_status_problem_problemname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='problems',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='judge.problem'),
        ),
    ]
