# Generated by Django 4.0.5 on 2022-07-05 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_alter_testcase_problems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='problems',
            new_name='problem',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='problems',
            new_name='problem',
        ),
    ]
