# Generated by Django 4.0.5 on 2022-07-05 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0006_rename_problems_submission_problem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='problem',
            new_name='problems',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='problem',
            new_name='problems',
        ),
    ]
