# Generated by Django 4.0.5 on 2022-07-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0008_rename_problems_submission_problem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(max_length=50),
        ),
    ]
