# Generated by Django 4.0.5 on 2022-07-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0010_userprofile_delete_user_remove_problem_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('compileCommand', models.TextField(null=True)),
                ('executeCommand', models.TextField(null=True)),
                ('dockerImage', models.TextField(null=True)),
                ('fileExtension', models.CharField(default='.cpp', max_length=255)),
            ],
        ),
    ]
