# Generated by Django 4.0.5 on 2022-07-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0012_executable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Executable',
            new_name='CodeRunner',
        ),
    ]
