# Generated by Django 4.0.5 on 2022-07-20 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0016_problem_editorial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coderunner',
            name='testCase',
        ),
        migrations.AddField(
            model_name='coderunner',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='judge.problem'),
            preserve_default=False,
        ),
    ]
